version: '3'
services:
  web:
    build: .
    ports:
    - "4000:4000"
    environment:
      RDB_HOST: rethinkdb
    links:
    - rethinkdb
    depends_on:
    - rethinkdb
    # restart: on-failure
    networks:
      - atx-network
  rethinkdb:
    image: rethinkdb:2.3.6
    networks:
      - atx-network
#    volumes:
#      - ./rethinkdb_data:/data
networks:
  atx-network:
    driver: bridge
    driver_opts:      
      "com.docker.network.bridge.enable_ip_masquerade": "true"
